# Generated by Django 5.0.6 on 2024-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=None, verbose_name='/file/')),
            ],
        ),
        migrations.DeleteModel(
            name='upload_file',
        ),
    ]
