# Generated by Django 5.0.6 on 2024-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare', '0002_file_model_delete_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
