# Generated by Django 5.0.6 on 2024-06-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare', '0003_alter_file_model_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_model',
            new_name='FileModel',
        ),
    ]
