# Generated by Django 5.0.6 on 2024-06-13 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileShare', '0004_rename_file_model_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
